/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;

/**
 *
 * @author Geral
 */
public class Exemplo4 extends javax.swing.JFrame {

    /**
     * Creates new form Exemplo4
     */
    public Exemplo4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCkbInglês = new javax.swing.JCheckBox();
        jCkbInformática = new javax.swing.JCheckBox();
        jBtnVerificar = new javax.swing.JButton();
        jBtnMarcar = new javax.swing.JButton();
        jBtnDesmarcar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jArquivo = new javax.swing.JMenu();
        jSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jCkbInglês.setText("Inglês");
        jCkbInglês.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCkbInglêsActionPerformed(evt);
            }
        });

        jCkbInformática.setText("Informática");
        jCkbInformática.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCkbInformáticaActionPerformed(evt);
            }
        });

        jBtnVerificar.setText("Verificar");
        jBtnVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnVerificarActionPerformed(evt);
            }
        });

        jBtnMarcar.setText("Marcar");
        jBtnMarcar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMarcarActionPerformed(evt);
            }
        });

        jBtnDesmarcar.setText("Desmarcar");
        jBtnDesmarcar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDesmarcarActionPerformed(evt);
            }
        });

        jArquivo.setText("Arquivo");
        jArquivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jArquivoMouseClicked(evt);
            }
        });
        jMenuBar1.add(jArquivo);

        jSair.setText("Sair");
        jSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSairMouseClicked(evt);
            }
        });
        jMenuBar1.add(jSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCkbInglês)
                    .addComponent(jCkbInformática)
                    .addComponent(jBtnVerificar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jBtnDesmarcar)
                        .addComponent(jBtnMarcar, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(274, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jCkbInglês)
                .addGap(18, 18, 18)
                .addComponent(jCkbInformática)
                .addGap(32, 32, 32)
                .addComponent(jBtnVerificar)
                .addGap(18, 18, 18)
                .addComponent(jBtnMarcar)
                .addGap(18, 18, 18)
                .addComponent(jBtnDesmarcar)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCkbInformáticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCkbInformáticaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCkbInformáticaActionPerformed

    private void jCkbInglêsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCkbInglêsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCkbInglêsActionPerformed

    private void jBtnDesmarcarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDesmarcarActionPerformed
        jCkbInformática.setSelected(false);
        jCkbInglês.setSelected(false);
// TODO add your handling code here:
    }//GEN-LAST:event_jBtnDesmarcarActionPerformed

    private void jBtnMarcarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMarcarActionPerformed
        jCkbInformática.setSelected(true);
        jCkbInglês.setSelected(true);
// TODO add your handling code here:
    }//GEN-LAST:event_jBtnMarcarActionPerformed

    private void jSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSairMouseClicked
        System.exit(0);// TODO add your handling code here:
    }//GEN-LAST:event_jSairMouseClicked

    private void jBtnVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnVerificarActionPerformed
        String selecao = "Selecionados ";
        if(jCkbInglês.isSelected()){
            selecao+= "\n"+jCkbInglês.getText();
        }
        if(jCkbInformática.isSelected()){
            selecao+= "\n"+jCkbInformática.getText();
            
        }
        JOptionPane.showMessageDialog(null, selecao);
            if((!jCkbInglês.isSelected()&&(!jCkbInformática.isSelected()))){
                JOptionPane.showMessageDialog(null, selecao);
            }else
                JOptionPane.showMessageDialog(null, "Nenhum curso selecionado!!!");   
    }//GEN-LAST:event_jBtnVerificarActionPerformed

    private void jArquivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jArquivoMouseClicked
        Exemplo5 tela = new Exemplo5();
        tela.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jArquivoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exemplo4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exemplo4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exemplo4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exemplo4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exemplo4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jArquivo;
    private javax.swing.JButton jBtnDesmarcar;
    private javax.swing.JButton jBtnMarcar;
    private javax.swing.JButton jBtnVerificar;
    private javax.swing.JCheckBox jCkbInformática;
    private javax.swing.JCheckBox jCkbInglês;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jSair;
    // End of variables declaration//GEN-END:variables
}
